name: Ping docs

on:
  push:
    branches: [ master ]

jobs:
  ping-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Ping docs
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.EZQUAKE_DOCS_REPO_ACCESS_TOKEN }}
          repository: vikpe/ezquake.github.io
          event-type: ezquake-updated
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
